# Makefile for environ

environ: environ.c
	gcc -o environ environ.c
	gcc -o getenv getenv.c
	gcc -o setenv setenv.c
	gcc -o putenv putenv.c
	gcc -o unsetenv unsetenv.c

clean:
	rm -f environ getenv setenv putenv unsetenv *~


